parameters:
    phpexcel.class:  Ephp\OfficeBundle\FactoryExcel
    phpword.class:  Ephp\OfficeBundle\FactoryWord

services:
    phpexcel:
      class: %phpexcel.class%
    phpword:
      class: %phpword.class%
